window.ROADMAP_STAGES = [
{
 id:"foundations",label:"01",title:"Foundations",desc:"Reconstruire le socle sans perdre du temps sur ce qui est déjà acquis.",
 modules:[
  {n:"01",title:"Diagnostic technique",type:"CORE",duration:"1–2 semaines",summary:"Mesurer le niveau réel avant de commencer.",learn:["TCP/IP, DNS, routing, NAT et filtrage","Git et ligne de commande","Virtualisation et mini-lab multi-machines"],practice:["Analyser une capture TCP dans Wireshark","Construire un petit réseau virtualisé","Expliquer le trajet DNS → TCP → HTTP"],exit:"Tu peux expliquer et diagnostiquer un flux réseau complet sans suivre un tutoriel.",resources:[["Wireshark","https://www.wireshark.org/docs/"],["RFC Editor","https://www.rfc-editor.org/"]]},
  {n:"02",title:"Linux fundamentals",type:"CORE",duration:"3–5 semaines",summary:"Retrouver une vraie autonomie Linux.",learn:["Filesystem, users, groups, UID/GID","Permissions, ACL, sudo, SUID","Processes, /proc, systemd, cron","SSH, logs, packages et networking"],practice:["Administrer une VM uniquement en CLI","Configurer utilisateurs, SSH, sudo et services","Écrire quelques scripts Bash d’administration"],exit:"Tu peux administrer et dépanner une VM Linux sans interface graphique.",resources:[["Linux man-pages","https://man7.org/linux/man-pages/"],["OverTheWire Bandit","https://overthewire.org/wargames/bandit/"]]},
  {n:"03",title:"Windows fundamentals",type:"CORE",duration:"3–5 semaines",summary:"Comprendre Windows comme système d’exploitation d’entreprise.",learn:["Users, groups, SID, SAM","NTFS, ACL, services, registry","Processes, tokens, UAC","SMB, RDP, WinRM, Event Logs"],practice:["Administrer une VM via PowerShell","Créer et tester des permissions NTFS","Observer les journaux générés par tes propres actions"],exit:"Tu peux expliquer identité, permissions, services et accès distant Windows.",resources:[["Windows Server","https://learn.microsoft.com/windows-server/"],["Sysinternals","https://learn.microsoft.com/sysinternals/"]]},
  {n:"04",title:"Networking for security",type:"CORE",duration:"2–4 semaines",summary:"Transformer les connaissances réseau en capacité d’analyse offensive.",learn:["ARP, ICMP, TCP/UDP, DNS, DHCP","VLAN, VPN, segmentation","Firewalls, NAT, proxy et tunnels","TLS et certificats"],practice:["Capturer et expliquer plusieurs protocoles","Créer deux zones réseau filtrées","Identifier pourquoi un service est joignable ou non"],exit:"À partir d’un symptôme réseau, tu sais formuler et tester plusieurs hypothèses.",resources:[["Wireshark","https://www.wireshark.org/docs/"],["RFC Editor","https://www.rfc-editor.org/"]]},
  {n:"05",title:"Scripting for pentesters",type:"CORE",duration:"4–6 semaines",summary:"Automatiser et comprendre les scripts que tu utilises.",learn:["Python : fonctions, modules, exceptions, venv","HTTP clients, sockets, JSON et parsing","Bash pipelines et scripts","PowerShell objets et remoting"],practice:["Créer un petit outil d’énumération de lab","Parser une sortie réseau en Python","Modifier un script existant en expliquant le changement"],exit:"Tu peux écrire un script utile de 100–200 lignes et le déboguer sans dépendance totale à l’IA.",resources:[["Python","https://docs.python.org/3/"],["PowerShell","https://learn.microsoft.com/powershell/"]]}
 ]
},
{
 id:"core",label:"02",title:"Core Pentest",desc:"Devenir autonome sur une cible et comprendre les grandes familles de vulnérabilités.",
 modules:[
  {n:"06",title:"Pentest methodology",type:"CORE",duration:"2–3 semaines",summary:"Passer de « lancer des outils » à une démarche reproductible.",learn:["Scope et Rules of Engagement","Recon, enumeration et attack surface","Observation → Hypothèse → Test","Evidence, impact, risk, remediation"],practice:["Écrire une checklist d’énumération","Tenir des notes horodatées","Produire un finding complet"],exit:"Tu peux expliquer pourquoi tu réalises chaque test et ce que son résultat change.",resources:[["NIST SP 800-115","https://csrc.nist.gov/pubs/sp/800/115/final"],["OWASP WSTG","https://wstg.owasp.org/"]]},
  {n:"07",title:"Recon & enumeration",type:"CORE",duration:"3–4 semaines",summary:"Transformer les signaux en hypothèses exploitables.",learn:["Nmap et fingerprinting","DNS, HTTP, TLS","SMB, SNMP, LDAP","Priorisation des hypothèses"],practice:["Scanner une cible puis vérifier manuellement","Cartographier services et versions","Produire une attack surface map"],exit:"Tu peux énumérer une cible sans sauter immédiatement sur une CVE.",resources:[["Nmap Reference","https://nmap.org/book/man.html"]]},
  {n:"08",title:"Web fundamentals",type:"CORE",duration:"3–5 semaines",summary:"Comprendre le navigateur, HTTP et les frontières de confiance du Web.",learn:["HTTP, headers, cookies, sessions","SOP, CORS, TLS","HTML, JavaScript, DOM","REST, JSON et API"],practice:["Rejouer des requêtes avec curl et Burp Repeater","Cartographier une application depuis son trafic","Expliquer une session de bout en bout"],exit:"Tu peux expliquer ce que le navigateur envoie, ce que le serveur reçoit et où se trouve l’état.",resources:[["MDN HTTP","https://developer.mozilla.org/docs/Web/HTTP"],["PortSwigger","https://portswigger.net/web-security"]]},
  {n:"09",title:"Web vulnerabilities",type:"CORE",duration:"8–12 semaines",summary:"Apprendre les classes majeures avec source → input → validation → sink → impact.",learn:["SQLi, XSS, IDOR","Auth et access control","Path traversal, file upload, LFI","Command injection, SSRF, XXE, SSTI"],practice:["Résoudre des labs sans lire la solution","Documenter cause racine et mitigation","Comparer plusieurs variantes d’une même vulnérabilité"],exit:"Tu peux reconnaître, confirmer et expliquer plusieurs classes de vulnérabilités sans payload magique.",resources:[["PortSwigger","https://portswigger.net/web-security"],["OWASP WSTG","https://wstg.owasp.org/"]]},
  {n:"10",title:"API security",type:"CORE",duration:"4–7 semaines",summary:"Étendre le raisonnement aux objets, rôles et workflows distribués.",learn:["BOLA/BFLA","JWT et OAuth/OIDC basics","GraphQL","Mass assignment, rate limits, business logic"],practice:["Cartographier une API","Tester contrôle d’accès objet/fonction","Construire un scénario d’abus multi-étapes"],exit:"Tu peux auditer une API en raisonnant sur objets, identités et flux métier.",resources:[["OWASP API Security","https://owasp.org/www-project-api-security/"]]},
  {n:"11",title:"Linux pentest & PrivEsc",type:"CORE",duration:"6–9 semaines",summary:"Du foothold à root en comprenant la faiblesse réelle.",learn:["Local enumeration","sudo, SUID, capabilities","cron, PATH, permissions","Credentials, NFS, containers"],practice:["10 cibles Linux indépendantes","5 analyses détaillées de PrivEsc","Comparer énumération manuelle et scripts automatisés"],exit:"Sur une cible de lab, tu peux obtenir root et expliquer précisément la chaîne de privilèges.",resources:[["GTFOBins","https://gtfobins.github.io/"]]},
  {n:"12",title:"Windows pentest & PrivEsc",type:"CORE",duration:"6–9 semaines",summary:"Comprendre services, permissions, tokens et identités locales.",learn:["Services et scheduled tasks","Registry et ACL","Tokens et privilèges","Credentials, SMB, WinRM, RDP"],practice:["10 cibles Windows","Analyse de permissions faibles","Observer la télémétrie de tes actions"],exit:"Sur un lab, tu peux passer d’un utilisateur faible à un contexte privilégié et expliquer pourquoi.",resources:[["Sysinternals","https://learn.microsoft.com/sysinternals/"],["LOLBAS","https://lolbas-project.github.io/"]]}
 ]
},
{
 id:"enterprise",label:"03",title:"Enterprise",desc:"Passer d’une machine à une infrastructure d’entreprise.",
 modules:[
  {n:"13",title:"Active Directory",type:"CORE",duration:"10–14 semaines",summary:"Comprendre AD comme graphe d’identités, permissions et relations.",learn:["Domain, DC, DNS, LDAP","Kerberos, NTLM, SID, SPN","Groups, GPO, ACL, trusts","Delegation et AD CS"],practice:["Construire un domaine de lab","Énumérer utilisateurs, groupes et relations","Étudier des attack paths multi-étapes"],exit:"Tu peux dessiner un domaine, expliquer Kerberos et identifier plusieurs chemins d’attaque réalistes.",resources:[["Microsoft AD DS","https://learn.microsoft.com/windows-server/identity/ad-ds/"],["MITRE ATT&CK","https://attack.mitre.org/"]]},
  {n:"14",title:"Infrastructure services",type:"CORE",duration:"4–7 semaines",summary:"Auditer les services comme systèmes de confiance, pas comme simples ports.",learn:["SMB, NFS, SSH, FTP","SMTP, DNS, SNMP","Databases et VPN","Segmentation et firewalls"],practice:["Créer une matrice service/auth/permission","Auditer un mini-réseau segmenté","Identifier exposition de secrets et réutilisation d’identités"],exit:"Tu peux analyser un service en termes d’authentification, autorisation, données et chemins de confiance.",resources:[["Nmap NSE","https://nmap.org/nsedoc/"],["CIS Benchmarks","https://www.cisecurity.org/cis-benchmarks"]]},
  {n:"15",title:"Pivoting & tunneling",type:"CORE",duration:"4–6 semaines",summary:"Atteindre des réseaux non directement accessibles sans perdre la compréhension du routage.",learn:["SSH local/remote/dynamic forwarding","SOCKS et proxying","Reverse tunnels","Routes et interfaces"],practice:["Lab attaquant → DMZ → réseau interne","Prouver le chemin du trafic avec capture","Maintenir plusieurs routes sans confusion"],exit:"Tu peux construire un pivot multi-réseaux et expliquer précisément le chemin de chaque flux.",resources:[["OpenSSH","https://www.openssh.com/manual.html"],["MITRE Proxy","https://attack.mitre.org/techniques/T1090/"]]},
  {n:"16",title:"Attack chains",type:"CORE",duration:"6–10 semaines",summary:"Combiner Web, systèmes, credentials, AD et pivoting.",learn:["Initial access","Credential access","Privilege escalation","Lateral movement","Impact minimal nécessaire"],practice:["Web → Linux → root","Credentials → Windows → AD","DMZ → pivot → internal"],exit:"Tu peux conduire et documenter une compromission multi-hôtes sans walkthrough.",resources:[["MITRE ATT&CK","https://attack.mitre.org/"]]},
  {n:"17",title:"Professional reporting",type:"CORE",duration:"continu",summary:"Transformer une compromission en décision de sécurité.",learn:["Evidence et reproductibilité","Impact technique et métier","Risk / CVSS","Executive summary et retest"],practice:["Écrire un rapport complet","Présenter oralement une chaîne d’attaque","Effectuer un retest"],exit:"Ton rapport permet à une équipe technique de reproduire, corriger et prioriser les problèmes.",resources:[["FIRST CVSS","https://www.first.org/cvss/"],["NIST SP 800-115","https://csrc.nist.gov/pubs/sp/800/115/final"]]}
 ]
},
{
 id:"advanced",label:"04",title:"Advanced & Specialization",desc:"Approfondir selon le métier visé sans abandonner les fondamentaux.",
 modules:[
  {n:"18",title:"Cloud & containers",type:"OPTION",duration:"6–10 semaines",summary:"IAM, workloads, Docker, Kubernetes et CI/CD.",learn:["Cloud IAM et rôles","Secrets et metadata","Docker isolation","Kubernetes RBAC et service accounts"],practice:["Lab container / Kubernetes","Cartographie IAM","Analyse d’un pipeline CI/CD de lab"],exit:"Tu peux représenter les identités et frontières de confiance d’une stack cloud/container.",resources:[["Kubernetes","https://kubernetes.io/docs/"],["OWASP Kubernetes Top 10","https://owasp.org/www-project-kubernetes-top-ten/"]]},
  {n:"19",title:"Exploit development foundations",type:"OPTION",duration:"8–16 semaines",summary:"Comprendre mémoire, exécution et mitigations bas niveau.",learn:["C et pointeurs","x86-64 assembly","Stack, heap, registers","ELF/PE, ASLR, NX, canaries, PIE"],practice:["GDB ou WinDbg","Challenges vulnérables dédiés","Étude de contrôle du flot"],exit:"Tu peux expliquer un crash, suivre le flot en debugger et comprendre l’effet des mitigations.",resources:[["pwn.college","https://pwn.college/"],["OST2","https://p.ost2.fyi/"]]},
  {n:"20",title:"Detection-aware offensive",type:"OPTION",duration:"4–8 semaines",summary:"Relier les techniques offensives à la télémétrie et à la détection.",learn:["Windows events / Sysmon","Network telemetry","Sigma","MITRE ATT&CK mapping"],practice:["Attaque contrôlée → logs → détection","Écrire quelques règles Sigma","Comparer endpoint et réseau"],exit:"Pour une technique offensive, tu sais dire quelles traces elle laisse et comment améliorer la détection.",resources:[["MITRE ATT&CK","https://attack.mitre.org/"],["Sigma","https://sigmahq.io/"]]}
 ]
}
];